import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { Shell } from "@/components/shell";
import { Button, Field, inputClass, cx } from "@/components/ui";
import { ensureSession, supabase } from "@/lib/supabase";

/**
 * Create-room page. Lists active games from Supabase, then creates a room for
 * the chosen game and adds the visitor as host. The room code is generated by
 * the database trigger, so it's read back from the inserted row.
 */
export const Route = createFileRoute("/play")({
  validateSearch: (search: Record<string, unknown>) => ({
    game: typeof search.game === "string" ? search.game : "",
  }),
  head: () => ({ meta: [{ title: "إنشاء غرفة — العش" }] }),
  component: CreatePage,
});

type GameRow = {
  id: string;
  slug: string;
  title_ar: string;
  description_ar: string;
  min_players: number;
  max_players: number;
};

type RoomRow = {
  id: string;
  room_code: string;
  game_id: string;
};

type PlayerRow = {
  id: string;
  player_name: string;
  is_host: boolean;
};

function CreatePage() {
  const { game: preselected } = Route.useSearch();
  const [games, setGames] = useState<GameRow[] | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [selected, setSelected] = useState<string>(preselected);
  const [hostName, setHostName] = useState("");
  const [busy, setBusy] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [room, setRoom] = useState<RoomRow | null>(null);
  const [players, setPlayers] = useState<PlayerRow[]>([]);

  // Load the active games (public read per RLS).
  useEffect(() => {
    if (!supabase) {
      setLoadError("الاتصال بقاعدة البيانات غير مضبوط بعد.");
      return;
    }
    supabase
      .from("games")
      .select("id, slug, title_ar, description_ar, min_players, max_players")
      .eq("is_active", true)
      .order("title_ar")
      .then(({ data, error }) => {
        if (error) setLoadError("تعذّر تحميل الألعاب، حاول مرة أخرى.");
        else setGames((data ?? []) as GameRow[]);
      });
  }, []);

  // Once a room exists, keep its player list current with a one-off read.
  // Realtime subscription comes in the next step.
  useEffect(() => {
    if (!supabase || !room) return;
    supabase
      .from("room_players")
      .select("id, player_name, is_host")
      .eq("room_id", room.id)
      .order("joined_at")
      .then(({ data }) => setPlayers((data ?? []) as PlayerRow[]));
  }, [room]);

  async function createRoom(event: FormEvent) {
    event.preventDefault();
    setFormError(null);
    const name = hostName.trim().replace(/\s+/g, " ");
    if (!selected) return setFormError("اختر لعبة أولاً.");
    if (name.length < 2 || name.length > 24) return setFormError("الاسم بين حرفين و24 حرفًا.");
    if (!supabase) return setFormError("الاتصال بقاعدة البيانات غير مضبوط بعد.");

    setBusy(true);
    try {
      const session = await ensureSession();
      const userId = session.user.id;

      // 1) Create the room. Its code is generated by the database trigger.
      const { data: created, error: roomError } = await supabase
        .from("game_rooms")
        .insert({ game_id: selected, settings: {} })
        .select("id, room_code, game_id")
        .single();
      if (roomError || !created) throw roomError ?? new Error("ROOM_CREATE_FAILED");
      const newRoom = created as RoomRow;

      // 2) Add the visitor as the host player.
      const { error: playerError } = await supabase.from("room_players").insert({
        room_id: newRoom.id,
        user_id: userId,
        player_name: name,
        is_host: true,
      });
      if (playerError) throw playerError;

      setRoom(newRoom);
    } catch (err) {
      setFormError(friendlyError(err));
    } finally {
      setBusy(false);
    }
  }

  if (room) {
    return (
      <Shell>
        <section className="glass-card mx-auto mt-6 max-w-xl rounded-3xl p-6 text-center">
          <p className="text-sm text-muted">رمز الغرفة</p>
          <p className="mt-2 font-mono text-4xl font-extrabold tracking-[0.3em] text-neon">{room.room_code}</p>
          <p className="mt-3 text-sm text-muted">شارك الرمز مع اللاعبين ليدخلوا من جوالاتهم.</p>

          <h2 className="mt-6 text-right text-base font-extrabold text-ivory">اللاعبون ({players.length})</h2>
          <ul className="mt-2 space-y-2 text-right">
            {players.map((p) => (
              <li key={p.id} className="flex items-center justify-between rounded-xl bg-white/[0.04] px-4 py-2 text-sm">
                <span className="text-ivory">{p.player_name}</span>
                {p.is_host ? <span className="text-xs font-bold text-violet">المضيف</span> : null}
              </li>
            ))}
          </ul>

          <Link to="/" className="mt-6 inline-flex min-h-11 items-center rounded-full border border-white/15 px-5 text-sm font-bold text-ivory">
            العودة للرئيسية
          </Link>
        </section>
      </Shell>
    );
  }

  return (
    <Shell>
      <section className="mx-auto mt-6 max-w-3xl">
        <h1 className="text-2xl font-extrabold text-ivory">إنشاء غرفة</h1>
        <p className="mt-2 text-sm text-muted">اختر اللعبة، واكتب اسمك، ثم افتح الغرفة.</p>

        {loadError ? (
          <p className="mt-6 rounded-2xl border border-crimson/40 bg-crimson/10 p-4 text-sm text-ivory">{loadError}</p>
        ) : games === null ? (
          <p className="mt-6 text-sm text-muted">جارٍ تحميل الألعاب…</p>
        ) : (
          <form onSubmit={createRoom} className="mt-6 space-y-6">
            <div className="grid gap-3 sm:grid-cols-2">
              {games.map((g) => (
                <button
                  key={g.id}
                  type="button"
                  onClick={() => setSelected(g.id)}
                  aria-pressed={selected === g.id}
                  className={cx(
                    "glass-card rounded-2xl p-4 text-right transition",
                    selected === g.id ? "border-neon/70 shadow-[0_0_0_3px_rgb(6_182_212/0.15)]" : "hover:border-neon/40",
                  )}
                >
                  <span className="block text-base font-extrabold text-ivory">{g.title_ar}</span>
                  <span className="mt-1 block text-sm leading-6 text-muted">{g.description_ar}</span>
                  <span className="mt-2 block text-xs font-bold text-muted">
                    👥 {g.min_players}–{g.max_players} لاعب
                  </span>
                </button>
              ))}
            </div>

            <Field label="اسمك (المضيف)">
              <input
                className={inputClass}
                value={hostName}
                onChange={(e) => setHostName(e.target.value)}
                maxLength={24}
                placeholder="اكتب اسمك"
                autoComplete="nickname"
              />
            </Field>

            {formError ? <p className="text-sm text-crimson">{formError}</p> : null}

            <Button type="submit" tone="primary" disabled={busy || !selected} className="w-full">
              {busy ? "جارٍ الإنشاء…" : "افتح الغرفة"}
            </Button>
          </form>
        )}
      </section>
    </Shell>
  );
}

function friendlyError(err: unknown): string {
  const message = err instanceof Error ? err.message : String((err as { message?: string })?.message ?? err);
  if (message.includes("SUPABASE_NOT_CONFIGURED")) return "الاتصال بقاعدة البيانات غير مضبوط بعد.";
  if (message.includes("ANON_SIGNIN_FAILED") || message.toLowerCase().includes("anonymous"))
    return "تعذّر تسجيل الدخول المؤقت. تأكد من تفعيل Anonymous Sign-Ins في Supabase.";
  if (message.includes("ROOM_FULL")) return "الغرفة ممتلئة.";
  if (message.includes("ROOM_FINISHED")) return "انتهت هذه الغرفة.";
  return "تعذّر إنشاء الغرفة، حاول مرة أخرى.";
}
