import { CATALOG } from "./catalog";
import type { Engine } from "./types";

export type SeedChoice = { id: string; ar: string; en: string; points?: number };
export type SeedQuestion = {
  promptAr: string;
  promptEn: string;
  kind: "mcq" | "text" | "feud" | "truth" | "choice" | "vote";
  choices?: SeedChoice[];
  correct?: string;
  accepted?: string[];
  difficulty?: "easy" | "medium" | "hard";
  icons?: string[];
  points?: number;
};

export type SeedGame = {
  id: string;
  nameAr: string;
  nameEn: string;
  descAr: string;
  descEn: string;
  category: string;
  tier: "free" | "premium";
  engine: Engine;
  minPlayers: number;
  maxPlayers: number;
  seconds: number;
  rounds: number;
  scoring: Record<string, number>;
  sort: number;
  icon: string;
  questions: SeedQuestion[];
};

const ids = ["a", "b", "c", "d"] as const;

function mcq(
  promptAr: string,
  promptEn: string,
  options: [string, string][],
  correct: number,
  difficulty: SeedQuestion["difficulty"] = "easy",
): SeedQuestion {
  return {
    promptAr,
    promptEn,
    kind: "mcq",
    difficulty,
    correct: ids[correct],
    choices: options.map(([ar, en], i) => ({ id: ids[i]!, ar, en })),
  };
}

function tf(promptAr: string, promptEn: string, yes: boolean, difficulty: SeedQuestion["difficulty"] = "easy"): SeedQuestion {
  return mcq(promptAr, promptEn, [
    ["صح", "True"],
    ["خطأ", "False"],
  ], yes ? 0 : 1, difficulty);
}

export const SEED_CATEGORIES = CATALOG.map((cat) => ({
  id: cat.id,
  ar: cat.ar,
  en: cat.en,
  sort: cat.sort,
}));

const letterRules = { unique: 10, duplicate: 5, wrong: 0, empty: 0 };

export const SEED_GAMES: SeedGame[] = [
  {
    id: "letter-names",
    nameAr: "اسم ولد بنت جماد حيوان بلد",
    nameEn: "Name, animal, place",
    descAr: "حرف واحد، خمس خانات، والإجابة الفريدة تغلب المكررة.",
    descEn: "One letter, five boxes. A unique answer scores more than a shared one.",
    category: "party",
    tier: "free",
    engine: "letter",
    minPlayers: 2,
    maxPlayers: 14,
    seconds: 60,
    rounds: 5,
    scoring: letterRules,
    sort: 1,
    icon: "Languages",
    questions: [],
  },
  {
    id: "general",
    nameAr: "معلومات عامة",
    nameEn: "General trivia",
    descAr: "أسئلة قصيرة من كل بحر، مناسبة للكبار والصغار.",
    descEn: "Short questions from every direction, fair for mixed ages.",
    category: "trivia",
    tier: "free",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 2,
    icon: "Brain",
    questions: [
      mcq("ما عاصمة فرنسا؟", "What is the capital of France?", [["باريس", "Paris"], ["ليون", "Lyon"], ["مرسيليا", "Marseille"], ["نيس", "Nice"]], 0),
      mcq("كم كوكبًا في المجموعة الشمسية؟", "How many planets are in the solar system?", [["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"]], 1),
      mcq("ما أسرع حيوان بري؟", "What is the fastest land animal?", [["الأسد", "Lion"], ["الفهد", "Cheetah"], ["الحصان", "Horse"], ["الغزال", "Gazelle"]], 1, "medium"),
      mcq("ما الرمز الكيميائي للماء؟", "What is the chemical symbol for water?", [["O2", "O2"], ["CO2", "CO2"], ["H2O", "H2O"], ["NaCl", "NaCl"]], 2),
      mcq("ما أكبر محيط على الأرض؟", "What is the largest ocean?", [["الأطلسي", "Atlantic"], ["الهندي", "Indian"], ["الهادئ", "Pacific"], ["المتجمد", "Arctic"]], 2, "medium"),
      mcq("كم ضلعًا في المثلث؟", "How many sides does a triangle have?", [["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], 1),
    ],
  },
  {
    id: "true-false",
    nameAr: "صح أو خطأ",
    nameEn: "True or false",
    descAr: "جملتان فقط: صح أو خطأ. سريعة ومناسبة للجولة الأولى.",
    descEn: "Two buttons. Fast rounds for the start of the night.",
    category: "trivia",
    tier: "free",
    engine: "truefalse",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 15,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 3,
    icon: "CircleHelp",
    questions: [
      tf("الرياض عاصمة المملكة العربية السعودية.", "Riyadh is the capital of Saudi Arabia.", true),
      tf("القمر يضيء من نفسه.", "The moon produces its own light.", false),
      tf("في السنة اثنا عشر شهرًا.", "A year has twelve months.", true),
      tf("الحوت من الأسماك.", "A whale is a fish.", false, "medium"),
      tf("الذهب فلز.", "Gold is a metal.", true, "medium"),
      tf("الشمس تدور حول الأرض.", "The sun orbits the earth.", false),
    ],
  },
  {
    id: "fastest",
    nameAr: "أسرع إجابة",
    nameEn: "Fastest answer",
    descAr: "الإجابة الصحيحة السريعة تأخذ نقاطًا أكثر.",
    descEn: "A correct answer is worth more when it arrives sooner.",
    category: "party",
    tier: "free",
    engine: "fastest",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 15,
    rounds: 8,
    scoring: { base: 400, speed: 600 },
    sort: 4,
    icon: "Zap",
    questions: [
      mcq("كم دقيقة في الساعة؟", "How many minutes are in an hour?", [["30", "30"], ["60", "60"], ["90", "90"], ["100", "100"]], 1),
      mcq("ما لون السماء الصافية نهارًا؟", "What color is a clear daytime sky?", [["أخضر", "Green"], ["أزرق", "Blue"], ["أحمر", "Red"], ["أسود", "Black"]], 1),
      mcq("2 + 2 × 2 = ؟", "2 + 2 × 2 = ?", [["6", "6"], ["8", "8"], ["4", "4"], ["2", "2"]], 0, "medium"),
      mcq("ما عاصمة اليابان؟", "What is the capital of Japan?", [["أوساكا", "Osaka"], ["كيوتو", "Kyoto"], ["طوكيو", "Tokyo"], ["هيروشيما", "Hiroshima"]], 2),
      mcq("كم يومًا في الأسبوع؟", "How many days are in a week?", [["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"]], 2),
    ],
  },
  {
    id: "who-knows",
    nameAr: "من يعرفني أكثر؟",
    nameEn: "Who knows me?",
    descAr: "واحد يجاوب عن نفسه، والبقية يحاولون يطابقونه.",
    descEn: "One player answers for themselves. Everyone else tries to match.",
    category: "party",
    tier: "free",
    engine: "whoknows",
    minPlayers: 2,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { match: 10, known: 5 },
    sort: 5,
    icon: "Heart",
    questions: [
      mcq("لو سافرت غدًا، تختار؟", "If you traveled tomorrow, you would pick?", [["البحر", "The sea"], ["الجبل", "The mountains"], ["مدينة", "A city"], ["البرية", "The desert"]], 0),
      mcq("وجبتك المفضلة أقرب إلى؟", "Your favorite meal is closer to?", [["كبسة", "Kabsa"], ["برجر", "Burger"], ["باستا", "Pasta"], ["سوشي", "Sushi"]], 0),
      mcq("تسهر ولا تصحى بدري؟", "Night owl or early riser?", [["سهر", "Night owl"], ["نوم مبكر", "Early riser"], ["حسب اليوم", "Depends"]], 0),
      mcq("قهوتك كيف؟", "How do you take coffee?", [["سادة", "Black"], ["بحليب", "With milk"], ["ما أشرب", "I don't"], ["مثلجة", "Iced"]], 0),
      mcq("في اللمة، دورك غالبًا؟", "At a gathering, you are usually?", [["المنظم", "The organizer"], ["المهرج", "The joker"], ["الهادئ", "The quiet one"], ["الطباخ", "The cook"]], 0),
    ],
  },
  {
    id: "most-likely",
    nameAr: "من الأكثر؟",
    nameEn: "Most likely",
    descAr: "صوّتوا لشخص في الغرفة. الأكثر أصواتًا يأخذ الجولة.",
    descEn: "Vote for someone in the room. The most votes takes the round.",
    category: "party",
    tier: "free",
    engine: "vote",
    minPlayers: 2,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { winner: 10 },
    sort: 6,
    icon: "Users",
    questions: [
      { promptAr: "من الأكثر تنظيمًا؟", promptEn: "Who is the most organized?", kind: "vote", difficulty: "easy" },
      { promptAr: "من الأكثر احتمالًا أن يتأخر؟", promptEn: "Who is most likely to arrive late?", kind: "vote", difficulty: "easy" },
      { promptAr: "من الأكثر مرحًا؟", promptEn: "Who is the most playful?", kind: "vote", difficulty: "easy" },
      { promptAr: "من الأكثر احتمالًا أن يفوز الليلة؟", promptEn: "Who is most likely to win tonight?", kind: "vote", difficulty: "easy" },
      { promptAr: "من الأكثر هدوءًا؟", promptEn: "Who is the calmest?", kind: "vote", difficulty: "easy" },
    ],
  },
  {
    id: "guess-character",
    nameAr: "خمن الشخصية",
    nameEn: "Guess the person",
    descAr: "تلميح قصير، وأربعة أسماء.",
    descEn: "A short clue and four names.",
    category: "trivia",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 7,
    icon: "Sparkles",
    questions: [
      mcq("من يُنسب إليه المصباح الكهربائي تجاريًا؟", "Who is credited with commercializing the light bulb?", [["أينشتاين", "Einstein"], ["إديسون", "Edison"], ["نيوتن", "Newton"], ["تسلا فقط", "Tesla only"]], 1, "medium"),
      mcq("من شارك في تأسيس أبل مع ستيف وزنياك؟", "Who co-founded Apple with Steve Wozniak?", [["بيل غيتس", "Bill Gates"], ["ستيف جوبز", "Steve Jobs"], ["مارك زوكربيرغ", "Mark Zuckerberg"], ["إيلون ماسك", "Elon Musk"]], 1),
      mcq("من أول إنسان صعد إلى الفضاء؟", "Who was the first human in space?", [["نيل أرمسترونغ", "Neil Armstrong"], ["يوري غاغارين", "Yuri Gagarin"], ["بز ألدرين", "Buzz Aldrin"], ["جون غلين", "John Glenn"]], 1, "hard"),
      mcq("من أخرج فيلم وجدة؟", "Who directed the film Wadjda?", [["هيفاء المنصور", "Haifaa Al-Mansour"], ["نادين لبكي", "Nadine Labaki"], ["آنجيلا", "Angela"], ["ميرفت", "Mervat"]], 0, "medium"),
      mcq("من القائد الذي فتح القدس عام 1187؟", "Who retook Jerusalem in 1187?", [["صلاح الدين", "Saladin"], ["طارق بن زياد", "Tariq ibn Ziyad"], ["خالد بن الوليد", "Khalid ibn al-Walid"], ["عمرو بن العاص", "Amr ibn al-As"]], 0, "medium"),
    ],
  },
  {
    id: "guess-picture",
    nameAr: "خمن الصورة",
    nameEn: "Guess the picture",
    descAr: "رموز كبيرة على التلفزيون، والاختيار من الجوال.",
    descEn: "Big symbols on the TV. Choices on the phone.",
    category: "party",
    tier: "premium",
    engine: "picture",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 8,
    icon: "Image",
    questions: [
      { ...mcq("ما المكان؟", "What place is this?", [["واحة", "An oasis"], ["مطار", "An airport"], ["مطبخ", "A kitchen"], ["ملعب", "A stadium"]], 0), icons: ["Palmtree", "Sun"] },
      { ...mcq("ما الشيء؟", "What is it?", [["قهوة", "Coffee"], ["عصير", "Juice"], ["ماء", "Water"], ["حليب", "Milk"]], 0), icons: ["Coffee"] },
      { ...mcq("ما النشاط؟", "What activity is this?", [["تخييم", "Camping"], ["سباحة", "Swimming"], ["طبخ", "Cooking"], ["قراءة", "Reading"]], 0), icons: ["Tent", "Moon"] },
      { ...mcq("ما الجهاز؟", "What is it?", [["لعبة فيديو", "A video game"], ["كتاب", "A book"], ["سيارة", "A car"], ["هاتف قديم", "An old phone"]], 0), icons: ["Gamepad2"] },
      { ...mcq("إلى أين؟", "Where to?", [["سفر", "Travel"], ["نوم", "Sleep"], ["دراسة", "Study"], ["رياضة", "Sport"]], 0), icons: ["Plane", "Compass"] },
    ],
  },
  {
    id: "proverb",
    nameAr: "أكمل المثل",
    nameEn: "Finish the proverb",
    descAr: "اكتب تكملة المثل. القريب من الصواب يُحتسب.",
    descEn: "Type the ending. A very close spelling still counts.",
    category: "arabic",
    tier: "premium",
    engine: "text",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 25,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 9,
    icon: "BookOpen",
    questions: [
      { promptAr: "أكمل: من جد …", promptEn: "Finish: hard work brings …", kind: "text", correct: "وجد", accepted: ["وجد", "الثمرة", "reward"], difficulty: "easy" },
      { promptAr: "أكمل: في التأني …", promptEn: "Finish: in patience there is …", kind: "text", correct: "السلامة", accepted: ["السلامة", "سلامة"], difficulty: "easy" },
      { promptAr: "أكمل: الصبر مفتاح …", promptEn: "Finish: patience is the key to …", kind: "text", correct: "الفرج", accepted: ["الفرج"], difficulty: "easy" },
      { promptAr: "أكمل: الوقت من …", promptEn: "Finish: time is …", kind: "text", correct: "ذهب", accepted: ["ذهب", "الذهب"], difficulty: "easy" },
      { promptAr: "أكمل: الطيور على أشكالها …", promptEn: "Finish: birds of a feather …", kind: "text", correct: "تقع", accepted: ["تقع"], difficulty: "medium" },
    ],
  },
  {
    id: "complete-word",
    nameAr: "أكمل الكلمة",
    nameEn: "Complete the word",
    descAr: "تعريف قصير، وتكتب الكلمة.",
    descEn: "A short clue. Type the word.",
    category: "arabic",
    tier: "premium",
    engine: "text",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 25,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 10,
    icon: "SpellCheck",
    questions: [
      { promptAr: "عاصمة المملكة: رـ ـ ـ ـ ض", promptEn: "Capital of the Kingdom.", kind: "text", correct: "الرياض", accepted: ["الرياض", "رياض"], difficulty: "easy" },
      { promptAr: "مشروب الضيافة العربية.", promptEn: "The drink of Arab hospitality.", kind: "text", correct: "قهوة", accepted: ["قهوة", "القهوة", "coffee"], difficulty: "easy" },
      { promptAr: "فاكهة حمراء من الخارج وخضراء من الداخل.", promptEn: "Red outside, green inside.", kind: "text", correct: "بطيخ", accepted: ["بطيخ", "البطيخ"], difficulty: "easy" },
      { promptAr: "مكان مرتفع من التراب والحجارة.", promptEn: "A high place of rock and earth.", kind: "text", correct: "جبل", accepted: ["جبل", "الجبل"], difficulty: "easy" },
      { promptAr: "عكس الطويل.", promptEn: "The opposite of tall.", kind: "text", correct: "قصير", accepted: ["قصير", "القصير"], difficulty: "easy" },
    ],
  },
  {
    id: "would-you",
    nameAr: "ماذا تختار؟",
    nameEn: "What would you pick?",
    descAr: "خياران، ولا إجابة خاطئة. الشاشة تعرض الانقسام.",
    descEn: "Two options, no wrong answer. The screen shows the split.",
    category: "party",
    tier: "premium",
    engine: "choice",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 15,
    rounds: 6,
    scoring: { answer: 5 },
    sort: 11,
    icon: "ListChecks",
    questions: [
      mcq("ماذا تختار؟", "What would you pick?", [["قهوة", "Coffee"], ["شاي", "Tea"]], 0),
      mcq("ماذا تختار؟", "What would you pick?", [["بحر", "Sea"], ["جبل", "Mountain"]], 0),
      mcq("ماذا تختار؟", "What would you pick?", [["فيلم", "A film"], ["مسلسل", "A series"]], 0),
      mcq("ماذا تختار؟", "What would you pick?", [["سفر", "Travel"], ["قعدة البيت", "A night in"]], 0),
      mcq("ماذا تختار؟", "What would you pick?", [["صباح", "Morning"], ["ليل", "Night"]], 0),
    ],
  },
  {
    id: "family",
    nameAr: "تحدي العائلة",
    nameEn: "Family challenge",
    descAr: "أسئلة تجمع الأجيال على طاولة واحدة.",
    descEn: "Questions that sit well between generations.",
    category: "family",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 25,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 12,
    icon: "Users",
    questions: [
      mcq("كم عدد أركان الإسلام؟", "How many pillars of Islam are there?", [["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"]], 2),
      mcq("كم فصلًا في السنة؟", "How many seasons are in a year?", [["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], 2),
      mcq("الكبسة أقرب إلى أي مطبخ؟", "Kabsa belongs most closely to which kitchen?", [["مغربي", "Moroccan"], ["سعودي", "Saudi"], ["تركي", "Turkish"], ["هندي", "Indian"]], 1),
      mcq("ما الشيء الذي يُقدَّم للضيف أولًا غالبًا؟", "What is usually offered to a guest first?", [["قهوة أو تمر", "Coffee or dates"], ["حلوى فقط", "Only dessert"], ["شوربة", "Soup"], ["عصير مصنع", "Bottled soda"]], 0),
      mcq("كم يومًا في شهر فبراير في السنة العادية؟", "How many days in February in a common year?", [["28", "28"], ["29", "29"], ["30", "30"], ["31", "31"]], 0, "medium"),
    ],
  },
  {
    id: "family-feud",
    nameAr: "عائلتي تربح",
    nameEn: "Family board",
    descAr: "اكتب إجابة يغلب أن يقولها الناس. الإجابة الأشهر نقاطها أعلى.",
    descEn: "Type what most people would say. Popular answers score more.",
    category: "family",
    tier: "premium",
    engine: "feud",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 30,
    rounds: 5,
    scoring: { half: 1 },
    sort: 13,
    icon: "Trophy",
    questions: [
      {
        promptAr: "أكلة سعودية مشهورة",
        promptEn: "A famous Saudi dish",
        kind: "feud",
        difficulty: "easy",
        choices: [
          { id: "a", ar: "كبسة", en: "Kabsa", points: 30 },
          { id: "b", ar: "مندي", en: "Mandi", points: 25 },
          { id: "c", ar: "جريش", en: "Jareesh", points: 20 },
          { id: "d", ar: "سليق", en: "Saleeg", points: 15 },
          { id: "e", ar: "مطبق", en: "Mutabbaq", points: 10 },
        ],
      },
      {
        promptAr: "شيء تأخذه معك في السفر",
        promptEn: "Something you pack for a trip",
        kind: "feud",
        choices: [
          { id: "a", ar: "جواز", en: "Passport", points: 30 },
          { id: "b", ar: "ملابس", en: "Clothes", points: 25 },
          { id: "c", ar: "شاحن", en: "Charger", points: 20 },
          { id: "d", ar: "نقود", en: "Money", points: 15 },
        ],
      },
      {
        promptAr: "مكان للخروج في الويكند",
        promptEn: "A weekend outing",
        kind: "feud",
        choices: [
          { id: "a", ar: "مول", en: "Mall", points: 30 },
          { id: "b", ar: "مطعم", en: "Restaurant", points: 25 },
          { id: "c", ar: "بحر", en: "Beach", points: 20 },
          { id: "d", ar: "بر", en: "Desert", points: 15 },
        ],
      },
    ],
  },
  {
    id: "saudi",
    nameAr: "تحدي السعودية",
    nameEn: "Saudi challenge",
    descAr: "مدن، تواريخ، وعادات من المملكة.",
    descEn: "Cities, dates, and customs from the Kingdom.",
    category: "saudi",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 14,
    icon: "Landmark",
    questions: [
      mcq("ما عاصمة المملكة العربية السعودية؟", "What is the capital of Saudi Arabia?", [["جدة", "Jeddah"], ["الرياض", "Riyadh"], ["مكة", "Makkah"], ["الدمام", "Dammam"]], 1),
      mcq("ما العملة الرسمية؟", "What is the official currency?", [["درهم", "Dirham"], ["دينار", "Dinar"], ["ريال", "Riyal"], ["جنيه", "Pound"]], 2),
      mcq("أي بحر يحد المملكة من الغرب؟", "Which sea borders the Kingdom on the west?", [["الخليج", "The Gulf"], ["الأحمر", "The Red Sea"], ["المتوسط", "Mediterranean"], ["العرب", "Arabian Sea"]], 1),
      mcq("في أي يوم يُحتفل باليوم الوطني؟", "When is Saudi National Day?", [["23 سبتمبر", "23 September"], ["23 مارس", "23 March"], ["1 يناير", "1 January"], ["18 ديسمبر", "18 December"]], 0, "medium"),
      mcq("مدينة الآثار والصخور في شمال غرب المملكة؟", "The heritage city of rock formations in the northwest?", [["أبها", "Abha"], ["العلا", "AlUla"], ["حائل", "Hail"], ["نجران", "Najran"]], 1),
      mcq("ما أعلى سلسلة جبلية في المملكة؟", "The main mountain range of the southwest?", [["السروات", "Sarawat"], ["الألب", "The Alps"], ["أطلس", "Atlas"], ["هيمالايا", "Himalaya"]], 0, "hard"),
    ],
  },
  {
    id: "football",
    nameAr: "كرة القدم",
    nameEn: "Football",
    descAr: "قوانين ومعلومات يعرفها جمهور الكرة.",
    descEn: "Rules and facts a match-day crowd would know.",
    category: "sport",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 15,
    icon: "Medal",
    questions: [
      mcq("كم لاعبًا أساسيًا في فريق كرة القدم؟", "How many players start for a football team?", [["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"]], 2),
      mcq("كم دقيقة في الشوط الواحد عادة؟", "How long is one half, usually?", [["30", "30"], ["40", "40"], ["45", "45"], ["60", "60"]], 2),
      mcq("كل كم سنة تُقام بطولة كأس العالم؟", "How often is the World Cup held?", [["سنتين", "2 years"], ["3 سنوات", "3 years"], ["4 سنوات", "4 years"], ["5 سنوات", "5 years"]], 2),
      mcq("أين أُقيمت كأس العالم 2022؟", "Where was the 2022 World Cup?", [["روسيا", "Russia"], ["قطر", "Qatar"], ["البرازيل", "Brazil"], ["ألمانيا", "Germany"]], 1),
      mcq("نادي الهلال ينتمي إلى أي مدينة؟", "Al-Hilal is based in which city?", [["جدة", "Jeddah"], ["الرياض", "Riyadh"], ["الدمام", "Dammam"], ["مكة", "Makkah"]], 1, "medium"),
    ],
  },
  {
    id: "screen",
    nameAr: "أفلام ومسلسلات",
    nameEn: "Film and series",
    descAr: "أسئلة خفيفة عن الشاشة، بلا حرق للأحداث.",
    descEn: "Light screen questions, without spoiling plots.",
    category: "entertainment",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 16,
    icon: "Film",
    questions: [
      mcq("استوديو الأنيميشن الذي أنتج Toy Story؟", "Which studio made Toy Story?", [["دريم ووركس", "DreamWorks"], ["بيكسار", "Pixar"], ["غيلبر", "Ghibli"], ["مارفل", "Marvel"]], 1),
      mcq("جائزة الأوسكار تُمنح في أي صناعة؟", "The Oscars belong to which industry?", [["الموسيقى", "Music"], ["السينما", "Film"], ["الرياضة", "Sport"], ["الأدب", "Literature"]], 1),
      mcq("سبايدرمان بطل من أي نوع؟", "Spider-Man is what kind of hero?", [["خارق", "A superhero"], ["تاريخي", "Historical"], ["رياضي", "An athlete"], ["طاهٍ", "A chef"]], 0),
      mcq("فيلم وجدة تدور أحداثه في أي مدينة؟", "Wadjda is set in which city?", [["دبي", "Dubai"], ["الرياض", "Riyadh"], ["القاهرة", "Cairo"], ["عمّان", "Amman"]], 1, "medium"),
      mcq("المسلسل الطويل Game of Thrones مبني على روايات من؟", "Game of Thrones is based on novels by?", [["تولكين", "Tolkien"], ["جورج مارتن", "George R. R. Martin"], ["رولينغ", "Rowling"], ["كريستين", "Christie"]], 1, "medium"),
    ],
  },
  {
    id: "videogames",
    nameAr: "ألعاب فيديو",
    nameEn: "Video games",
    descAr: "من ماريو إلى ماينكرافت، بلا أسئلة تعجيزية.",
    descEn: "From Mario to Minecraft, without obscurities.",
    category: "entertainment",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 17,
    icon: "Gamepad2",
    questions: [
      mcq("ماريو شخصية تتبع أي شركة؟", "Mario belongs to which company?", [["سوني", "Sony"], ["نينتندو", "Nintendo"], ["مايكروسوفت", "Microsoft"], ["سيجا فقط", "Sega only"]], 1),
      mcq("لعبة المكعبات والبناء الشهيرة؟", "The famous block-building game?", [["فيفا", "FIFA"], ["ماينكرافت", "Minecraft"], ["كلّا أوف دوتي", "Call of Duty"], ["كاندي كراش", "Candy Crush"]], 1),
      mcq("بلايستيشن جهاز من أي شركة؟", "PlayStation is made by?", [["نينتندو", "Nintendo"], ["سوني", "Sony"], ["أبل", "Apple"], ["سامسونغ", "Samsung"]], 1),
      mcq("فورتنايت اشتهرت بأي نمط؟", "Fortnite is famous for which mode?", [["باتل رويال", "Battle royale"], ["سباق سيارات فقط", "Racing only"], ["شطرنج", "Chess"], ["كرة مضرب", "Tennis"]], 0, "medium"),
      mcq("كم لاعبًا في فريق كرة القدم داخل فيفا عادة في الملعب؟", "How many players per side are on the pitch in FIFA?", [["5", "5"], ["7", "7"], ["11", "11"], ["15", "15"]], 2),
    ],
  },
  {
    id: "kids",
    nameAr: "تحدي الأطفال",
    nameEn: "Kids challenge",
    descAr: "أسئلة سهلة وواضحة حتى يلعب الصغير مع الكبير.",
    descEn: "Clear, easy questions so younger players can join.",
    category: "kids",
    tier: "free",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 25,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 18,
    icon: "Baby",
    questions: [
      mcq("ما لون الموز الناضج؟", "What color is a ripe banana?", [["أزرق", "Blue"], ["أصفر", "Yellow"], ["أسود", "Black"], ["بنفسجي", "Purple"]], 1),
      mcq("الحيوان الذي يقول مواء؟", "Which animal says meow?", [["الكلب", "Dog"], ["القطة", "Cat"], ["البقرة", "Cow"], ["الأسد", "Lion"]], 1),
      mcq("كم يساوي 2 + 2؟", "What is 2 + 2?", [["3", "3"], ["4", "4"], ["5", "5"], ["22", "22"]], 1),
      mcq("كم يومًا في الأسبوع؟", "How many days are in a week?", [["5", "5"], ["6", "6"], ["7", "7"], ["10", "10"]], 2),
      mcq("الشمس تطلع في؟", "The sun rises in the?", [["الليل فقط", "Only at night"], ["الصباح", "Morning"], ["منتصف الليل", "Midnight"], ["ما تطلع", "It doesn't"]], 1),
    ],
  },
  {
    id: "truth-dare",
    nameAr: "صراحة أو تحدي",
    nameEn: "Truth or dare",
    descAr: "تحديات عائلية خفيفة. المضيف يستطيع إضافة نقاط إذا نُفِّذ التحدي.",
    descEn: "Light, family-safe prompts. The host can bonus a completed dare.",
    category: "party",
    tier: "premium",
    engine: "truth",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { pick: 5, bonus: 10 },
    sort: 19,
    icon: "MessageCircle",
    questions: [
      {
        promptAr: "اختر",
        promptEn: "Choose",
        kind: "truth",
        choices: [
          { id: "truth", ar: "صراحة: ما أغرب أكل جربته؟", en: "Truth: what is the oddest food you have tried?" },
          { id: "dare", ar: "تحدي: قلّد صوت حيوان لعشر ثوانٍ.", en: "Dare: imitate an animal for ten seconds." },
        ],
      },
      {
        promptAr: "اختر",
        promptEn: "Choose",
        kind: "truth",
        choices: [
          { id: "truth", ar: "صراحة: آخر شيء ضحكت عليه اليوم؟", en: "Truth: what last made you laugh today?" },
          { id: "dare", ar: "تحدي: غنِّ سطرًا واحدًا.", en: "Dare: sing a single line." },
        ],
      },
      {
        promptAr: "اختر",
        promptEn: "Choose",
        kind: "truth",
        choices: [
          { id: "truth", ar: "صراحة: ما عادة صغيرة تسعدك؟", en: "Truth: what small habit makes you happy?" },
          { id: "dare", ar: "تحدي: امدح الشخص الذي على يمينك.", en: "Dare: compliment the person to your right." },
        ],
      },
      {
        promptAr: "اختر",
        promptEn: "Choose",
        kind: "truth",
        choices: [
          { id: "truth", ar: "صراحة: قهوة ولا شاي، ولماذا باختصار؟", en: "Truth: coffee or tea, and why in one line?" },
          { id: "dare", ar: "تحدي: اصنع أطرف وجه للكاميرا.", en: "Dare: pull your funniest face to the camera." },
        ],
      },
    ],
  },
  {
    id: "friends",
    nameAr: "تحدي الأصدقاء",
    nameEn: "Friends challenge",
    descAr: "معلومات خفيفة يعرفها ربع اللمة.",
    descEn: "Light facts a group of friends would argue over.",
    category: "party",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 8,
    scoring: { correct: 10, wrong: 0 },
    sort: 20,
    icon: "Mic",
    questions: [
      mcq("تطبيق المقاطع القصيرة الأشهر؟", "The best-known short-video app?", [["تيك توك", "TikTok"], ["وورد", "Word"], ["خرائط", "Maps"], ["بريد", "Mail"]], 0),
      mcq("كم ساعة في اليوم؟", "How many hours are in a day?", [["12", "12"], ["20", "20"], ["24", "24"], ["48", "48"]], 2),
      mcq("GIF عادةً تكون؟", "A GIF is usually?", [["صورة متحركة قصيرة", "A short animation"], ["ملف صوت", "An audio file"], ["جدول", "A spreadsheet"], ["خريطة", "A map"]], 0, "medium"),
      mcq("الواي فاي يوصل؟", "Wi-Fi connects you to?", [["الكهرباء فقط", "Only electricity"], ["الإنترنت لاسلكيًا", "The internet wirelessly"], ["الماء", "Water"], ["الغاز", "Gas"]], 1),
      mcq("الإيموجي الأصفر الضاحك يعبر غالبًا عن؟", "The yellow laughing face usually means?", [["حزن", "Sadness"], ["ضحك", "Laughter"], ["جوع", "Hunger"], ["برد", "Cold"]], 1),
    ],
  },
  {
    id: "animals",
    nameAr: "عالم الحيوان",
    nameEn: "Animal world",
    descAr: "أسئلة واضحة عن الحيوانات، تناسب الصغير والكبير.",
    descEn: "Clear animal questions for mixed ages.",
    category: "kids",
    tier: "free",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 21,
    icon: "PawPrint",
    questions: [
      mcq("ما الحيوان صاحب أطول رقبة؟", "Which animal has the longest neck?", [["الفيل", "Elephant"], ["الزرافة", "Giraffe"], ["الجمل", "Camel"], ["الحصان", "Horse"]], 1),
      mcq("ما أكبر حيوان يعيش على الأرض؟", "What is the largest animal on earth?", [["الفيل", "Elephant"], ["القرش", "Shark"], ["الحوت الأزرق", "Blue whale"], ["الدب", "Bear"]], 2),
      mcq("أي طائر مشهور بأنه لا يطير؟", "Which bird is famous for not flying?", [["النعامة", "Ostrich"], ["النسر", "Eagle"], ["العصفور", "Sparrow"], ["البجع", "Pelican"]], 0),
      mcq("ما الحيوان الذي يُضرب به المثل في السرعة؟", "Which animal is the proverb for speed?", [["السلحفاة", "Turtle"], ["الفهد", "Cheetah"], ["البقر", "Cow"], ["الحلزون", "Snail"]], 1),
      mcq("أين يعيش السمك؟", "Where does a fish live?", [["في الجحر", "In a burrow"], ["في الماء", "In water"], ["على الشجر", "In trees"], ["في العش", "In a nest"]], 1),
      mcq("الحيوان الذي يقول مواء؟", "Which animal says meow?", [["الكلب", "Dog"], ["القطة", "Cat"], ["الحصان", "Horse"], ["الخروف", "Sheep"]], 1),
    ],
  },
  {
    id: "colors",
    nameAr: "ألوان",
    nameEn: "Colors",
    descAr: "ألوان وأشكال بسيطة، جولة هادئة قبل الأسئلة الأصعب.",
    descEn: "Simple colors and mixes, a calm round before harder questions.",
    category: "kids",
    tier: "free",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 15,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 22,
    icon: "Palette",
    questions: [
      mcq("خلط الأصفر مع الأزرق يعطي؟", "Yellow mixed with blue makes?", [["أحمر", "Red"], ["أخضر", "Green"], ["أسود", "Black"], ["برتقالي", "Orange"]], 1),
      mcq("ما لون الموز الناضج؟", "What color is a ripe banana?", [["أزرق", "Blue"], ["أصفر", "Yellow"], ["بنفسجي", "Purple"], ["رمادي", "Gray"]], 1),
      mcq("ما لون الثلج؟", "What color is snow?", [["أسود", "Black"], ["أحمر", "Red"], ["أبيض", "White"], ["بني", "Brown"]], 2),
      mcq("السماء الصافية نهارًا لونها؟", "A clear daytime sky is?", [["أخضر", "Green"], ["أزرق", "Blue"], ["أصفر", "Yellow"], ["وردي", "Pink"]], 1),
      mcq("خلط الأحمر مع الأصفر يعطي؟", "Red mixed with yellow makes?", [["برتقالي", "Orange"], ["أزرق", "Blue"], ["أسود", "Black"], ["أبيض", "White"]], 0, "medium"),
      mcq("ما لون الورق السليم في الشجرة؟", "A healthy leaf is usually?", [["أزرق", "Blue"], ["أخضر", "Green"], ["أبيض", "White"], ["رمادي", "Gray"]], 1),
    ],
  },
  {
    id: "math-dash",
    nameAr: "سباق الحساب",
    nameEn: "Math dash",
    descAr: "عمليات قصيرة. الأسرع بإجابة صحيحة يأخذ نقاطًا أكثر.",
    descEn: "Short sums. A faster correct answer is worth more.",
    category: "trivia",
    tier: "free",
    engine: "fastest",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 12,
    rounds: 8,
    scoring: { base: 400, speed: 600 },
    sort: 23,
    icon: "Calculator",
    questions: [
      mcq("5 × 5 = ؟", "5 × 5 = ?", [["20", "20"], ["25", "25"], ["30", "30"], ["15", "15"]], 1),
      mcq("9 + 8 = ؟", "9 + 8 = ?", [["17", "17"], ["18", "18"], ["16", "16"], ["19", "19"]], 0),
      mcq("100 ÷ 4 = ؟", "100 ÷ 4 = ?", [["20", "20"], ["25", "25"], ["40", "40"], ["50", "50"]], 1),
      mcq("3 × 7 = ؟", "3 × 7 = ?", [["18", "18"], ["20", "20"], ["21", "21"], ["24", "24"]], 2),
      mcq("20 − 6 = ؟", "20 − 6 = ?", [["12", "12"], ["14", "14"], ["16", "16"], ["26", "26"]], 1),
      mcq("نصف الخمسين؟", "Half of fifty?", [["20", "20"], ["25", "25"], ["30", "30"], ["15", "15"]], 1),
    ],
  },
  {
    id: "capitals",
    nameAr: "عواصم",
    nameEn: "Capitals",
    descAr: "عواصم يعرفها أغلب الجالسين، وفيها مفاجأة أو اثنتان.",
    descEn: "Capitals most of the room will know, with one or two traps.",
    category: "trivia",
    tier: "free",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 18,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 24,
    icon: "Globe",
    questions: [
      mcq("ما عاصمة مصر؟", "What is the capital of Egypt?", [["الإسكندرية", "Alexandria"], ["القاهرة", "Cairo"], ["الأقصر", "Luxor"], ["أسوان", "Aswan"]], 1),
      mcq("ما عاصمة اليابان؟", "What is the capital of Japan?", [["أوساكا", "Osaka"], ["كيوتو", "Kyoto"], ["طوكيو", "Tokyo"], ["هيروشيما", "Hiroshima"]], 2),
      mcq("ما عاصمة إيطاليا؟", "What is the capital of Italy?", [["ميلانو", "Milan"], ["روما", "Rome"], ["البندقية", "Venice"], ["نابولي", "Naples"]], 1),
      mcq("ما عاصمة بريطانيا؟", "What is the capital of Britain?", [["مانشستر", "Manchester"], ["لندن", "London"], ["ليفربول", "Liverpool"], ["إدنبرة", "Edinburgh"]], 1),
      mcq("ما عاصمة تركيا؟", "What is the capital of Turkey?", [["إسطنبول", "Istanbul"], ["أنطاليا", "Antalya"], ["أنقرة", "Ankara"], ["إزمير", "Izmir"]], 2, "medium"),
      mcq("ما عاصمة المغرب؟", "What is the capital of Morocco?", [["مراكش", "Marrakesh"], ["فاس", "Fes"], ["الدار البيضاء", "Casablanca"], ["الرباط", "Rabat"]], 3, "medium"),
    ],
  },
  {
    id: "council",
    nameAr: "في المجلس",
    nameEn: "In the majlis",
    descAr: "صوّتوا على شخص في الغرفة. الأكثر أصواتًا يفوز بالجولة.",
    descEn: "Vote for someone in the room. The most votes wins the round.",
    category: "party",
    tier: "free",
    engine: "vote",
    minPlayers: 3,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { winner: 10 },
    sort: 25,
    icon: "House",
    questions: [
      { promptAr: "من يرد أولًا إذا رن الجوال؟", promptEn: "Who answers the phone first?", kind: "vote", difficulty: "easy" },
      { promptAr: "من يطلب الزيادة من الأكل؟", promptEn: "Who asks for a second serving?", kind: "vote", difficulty: "easy" },
      { promptAr: "من يصوّر أكثر لقطة؟", promptEn: "Who takes the most photos?", kind: "vote", difficulty: "easy" },
      { promptAr: "من ينام أول واحد؟", promptEn: "Who falls asleep first?", kind: "vote", difficulty: "easy" },
      { promptAr: "من يختار المطعم؟", promptEn: "Who picks the restaurant?", kind: "vote", difficulty: "easy" },
      { promptAr: "من يضيع المفاتيح؟", promptEn: "Who loses the keys?", kind: "vote", difficulty: "easy" },
    ],
  },
  {
    id: "kitchen",
    nameAr: "تحدي المطبخ",
    nameEn: "Kitchen challenge",
    descAr: "أكلات وبهارات من المائدة، بلا أسئلة تعجيزية.",
    descEn: "Dishes and spices from the table, without trick questions.",
    category: "family",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 26,
    icon: "UtensilsCrossed",
    questions: [
      mcq("التمر ثمر أي شجرة؟", "Dates grow on which tree?", [["الزيتون", "Olive"], ["النخلة", "Palm"], ["التفاح", "Apple"], ["الرمان", "Pomegranate"]], 1),
      mcq("الجريش يُصنع أساسًا من؟", "Jareesh is made mainly from?", [["الأرز", "Rice"], ["القمح", "Wheat"], ["الذرة", "Corn"], ["العدس", "Lentils"]], 1),
      mcq("الكمون يُصنَّف كـ؟", "Cumin is best described as?", [["فاكهة", "A fruit"], ["بهار", "A spice"], ["شراب", "A drink"], ["خبز", "A bread"]], 1),
      mcq("السليق أساسه غالبًا؟", "Saleeg is usually based on?", [["المعكرونة", "Pasta"], ["الأرز والحليب", "Rice and milk"], ["الخبز فقط", "Bread only"], ["السمك", "Fish"]], 1, "medium"),
      mcq("ماذا يُقدَّم مع القهوة العربية غالبًا؟", "What is usually served with Arabic coffee?", [["الآيس كريم", "Ice cream"], ["التمر", "Dates"], ["البيتزا", "Pizza"], ["الشوربة", "Soup"]], 1),
      mcq("المندي طريقة طبخه التقليدية أقرب إلى؟", "Traditional mandi is cooked closest to?", [["القلي السريع", "A quick fry"], ["التنور", "A tannour oven"], ["السلق فقط", "Boiling only"], ["التبريد", "Chilling"]], 1, "medium"),
    ],
  },
  {
    id: "science",
    nameAr: "علوم خفيفة",
    nameEn: "Light science",
    descAr: "حقائق مدرسية ما زالت حاضرة في المجلس.",
    descEn: "School facts that still come up around the table.",
    category: "trivia",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 27,
    icon: "FlaskConical",
    questions: [
      mcq("ما أقرب نجم إلى الأرض؟", "What is the nearest star to Earth?", [["القمر", "The moon"], ["الشمس", "The sun"], ["المريخ", "Mars"], ["الزهرة", "Venus"]], 1),
      mcq("الغاز الذي نتنفسه بكثرة في الهواء؟", "The gas we breathe in from the air?", [["النيتروجين فقط", "Only nitrogen"], ["الأكسجين", "Oxygen"], ["الهيدروجين", "Hydrogen"], ["الهيليوم", "Helium"]], 1),
      mcq("درجة غليان الماء عند سطح البحر تقريبًا؟", "Water boils at sea level at about?", [["50°", "50°"], ["80°", "80°"], ["100°", "100°"], ["200°", "200°"]], 2),
      mcq("أيهما أسرع؟", "Which is faster?", [["الصوت", "Sound"], ["الضوء", "Light"], ["الريح دائمًا", "Wind, always"], ["متساويان", "They are equal"]], 1, "medium"),
      mcq("الجاذبية تسحب الأشياء نحو؟", "Gravity pulls objects toward?", [["السماء", "The sky"], ["مركز الأرض", "Earth's center"], ["القمر فقط", "Only the moon"], ["الشمال", "North"]], 1),
      mcq("الماء في حالته الصلبة يسمى؟", "Solid water is called?", [["بخار", "Steam"], ["ثلج", "Ice"], ["ملح", "Salt"], ["زيت", "Oil"]], 1),
    ],
  },
  {
    id: "geo",
    nameAr: "جغرافيا",
    nameEn: "Geography",
    descAr: "قارات وبحار وخطوط، بمستوى مجلس لا اختبار.",
    descEn: "Continents, seas, and lines, at living-room level.",
    category: "trivia",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 28,
    icon: "Map",
    questions: [
      mcq("ما أكبر قارة؟", "What is the largest continent?", [["أوروبا", "Europe"], ["أفريقيا", "Africa"], ["آسيا", "Asia"], ["أستراليا", "Australia"]], 2),
      mcq("النهر الذي يمر بمصر؟", "The river that runs through Egypt?", [["الأمازون", "The Amazon"], ["النيل", "The Nile"], ["الدانوب", "The Danube"], ["الفرات", "The Euphrates"]], 1),
      mcq("الصحراء الكبرى تقع في؟", "The Sahara is in?", [["آسيا", "Asia"], ["أفريقيا", "Africa"], ["أوروبا", "Europe"], ["أمريكا", "The Americas"]], 1),
      mcq("خط الاستواء يقسم الأرض إلى؟", "The equator divides Earth into?", [["شرق وغرب", "East and west"], ["شمال وجنوب", "North and south"], ["بر وبحر", "Land and sea"], ["ليل ونهار", "Night and day"]], 1, "medium"),
      mcq("أي قارة تغطيها الثلوج في أغلبها؟", "Which continent is mostly covered in ice?", [["أفريقيا", "Africa"], ["أنتاركتيكا", "Antarctica"], ["أوروبا", "Europe"], ["آسيا", "Asia"]], 1, "medium"),
      mcq("البحر الأحمر يقع بين أفريقيا و؟", "The Red Sea lies between Africa and?", [["أوروبا", "Europe"], ["شبه الجزيرة العربية", "The Arabian Peninsula"], ["الهند", "India"], ["أمريكا", "The Americas"]], 1),
    ],
  },
  {
    id: "music",
    nameAr: "موسيقى",
    nameEn: "Music",
    descAr: "آلات وإيقاع، بلا أسئلة عن تواريخ الحفلات.",
    descEn: "Instruments and rhythm, not tour dates.",
    category: "entertainment",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 20,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 29,
    icon: "Music",
    questions: [
      mcq("العود آلة؟", "The oud is what kind of instrument?", [["إيقاع", "Percussion"], ["وترية", "A string instrument"], ["نفخ نحاسية فقط", "Only brass"], ["إلكترونية حصرًا", "Only electronic"]], 1),
      mcq("الطبل يُستخدم غالبًا في؟", "A drum is mostly used for?", [["الإيقاع", "Rhythm"], ["الكتابة", "Writing"], ["الإضاءة", "Lighting"], ["الطبخ", "Cooking"]], 0),
      mcq("أم كلثوم مطربة من؟", "Umm Kulthum was a singer from?", [["المغرب", "Morocco"], ["مصر", "Egypt"], ["لبنان فقط", "Lebanon only"], ["الهند", "India"]], 1),
      mcq("البيانو يُعزف بـ؟", "A piano is played with?", [["الأقدام فقط", "Only the feet"], ["ضغط المفاتيح", "Pressing keys"], ["النفخ", "Blowing"], ["الوتر والقوس فقط", "A bow only"]], 1),
      mcq("النوتة تُكتب عادة على؟", "Notes are usually written on?", [["مدرج موسيقي", "A staff"], ["خريطة", "A map"], ["جدول ضرب", "A times table"], ["قائمة طعام", "A menu"]], 1, "medium"),
      mcq("الأغنية بلا كلام تسمى غالبًا؟", "A piece with no singing is often called?", [["معزوفة", "An instrumental"], ["قصيدة فقط", "Only a poem"], ["حوار", "A dialogue"], ["خبر", "A news item"]], 0, "medium"),
    ],
  },
  {
    id: "cars",
    nameAr: "سيارات",
    nameEn: "Cars",
    descAr: "قواعد الطريق وأساسيات السيارة، يعرفها من يقود ومن يركب.",
    descEn: "Road rules and car basics, for drivers and passengers.",
    category: "entertainment",
    tier: "premium",
    engine: "quiz",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 18,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 30,
    icon: "Car",
    questions: [
      mcq("كم عجلة في السيارة العادية؟", "How many wheels on an ordinary car?", [["2", "2"], ["3", "3"], ["4", "4"], ["6", "6"]], 2),
      mcq("إشارة الضوء الأحمر تعني؟", "A red traffic light means?", [["سر", "Go"], ["قف", "Stop"], ["استدر للخلف فورًا", "Reverse at once"], ["أطفئ المحرك", "Switch the engine off"]], 1),
      mcq("المقود يتحكم في؟", "The steering wheel controls?", [["الصوت", "The volume"], ["الاتجاه", "Direction"], ["المكيف فقط", "Only the air conditioning"], ["الإنارة الداخلية", "Only the cabin light"]], 1),
      mcq("حزام الأمان يُربط؟", "A seatbelt is fastened?", [["بعد الوصول", "After you arrive"], ["قبل الانطلاق", "Before you move"], ["عند المطر فقط", "Only in rain"], ["ما له لزوم", "Never"]], 1),
      mcq("الفورمولا سباق لـ؟", "Formula racing is a race of?", [["الخيل", "Horses"], ["السيارات", "Cars"], ["القوارب فقط", "Boats only"], ["الدراجات الهوائية حصرًا", "Only bicycles"]], 1),
      mcq("وقود أغلب السيارات التقليدية؟", "Most conventional cars run on?", [["ماء", "Water"], ["بنزين أو ديزل", "Petrol or diesel"], ["حبر", "Ink"], ["ملح", "Salt"]], 1, "medium"),
    ],
  },
  {
    id: "riddles",
    nameAr: "ألغاز",
    nameEn: "Riddles",
    descAr: "لغز قصير، وتكتب الكلمة. الإملاء القريب يُحتسب.",
    descEn: "A short riddle. Type the word. A close spelling still counts.",
    category: "arabic",
    tier: "premium",
    engine: "text",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 30,
    rounds: 6,
    scoring: { correct: 10, wrong: 0 },
    sort: 31,
    icon: "Lightbulb",
    questions: [
      { promptAr: "له أوراق وليس نباتًا.", promptEn: "It has leaves and is not a plant.", kind: "text", correct: "الكتاب", accepted: ["كتاب", "الكتاب"], difficulty: "easy" },
      { promptAr: "له أسنان ولا يعض.", promptEn: "It has teeth and does not bite.", kind: "text", correct: "المشط", accepted: ["مشط", "المشط"], difficulty: "easy" },
      { promptAr: "يمشي بلا قدمين.", promptEn: "It walks without feet.", kind: "text", correct: "الساعة", accepted: ["ساعة", "الساعة"], difficulty: "medium" },
      { promptAr: "يكتب ولا يقرأ.", promptEn: "It writes and cannot read.", kind: "text", correct: "القلم", accepted: ["قلم", "القلم"], difficulty: "easy" },
      { promptAr: "كلما أخذت منه كبر.", promptEn: "The more you take from it, the bigger it gets.", kind: "text", correct: "الحفرة", accepted: ["حفرة", "الحفرة"], difficulty: "medium" },
      { promptAr: "يملأ الغرفة ولا يأخذ مكانًا.", promptEn: "It fills a room and takes no space.", kind: "text", correct: "النور", accepted: ["نور", "النور", "الضوء", "ضوء"], difficulty: "medium" },
    ],
  },
  {
    id: "this-or-that",
    nameAr: "هذا ولا هذا",
    nameEn: "This or that",
    descAr: "خياران ولا إجابة خاطئة. الشاشة تعرض انقسام الغرفة.",
    descEn: "Two options, no wrong answer. The screen shows the split.",
    category: "party",
    tier: "premium",
    engine: "choice",
    minPlayers: 1,
    maxPlayers: 14,
    seconds: 15,
    rounds: 6,
    scoring: { answer: 5 },
    sort: 32,
    icon: "Scale",
    questions: [
      mcq("هذا ولا هذا؟", "This or that?", [["كبسة", "Kabsa"], ["مندي", "Mandi"]], 0),
      mcq("هذا ولا هذا؟", "This or that?", [["بحر", "Sea"], ["بر", "Desert"]], 0),
      mcq("هذا ولا هذا؟", "This or that?", [["فيلم", "A film"], ["مسلسل", "A series"]], 0),
      mcq("هذا ولا هذا؟", "This or that?", [["قهوة عربية", "Arabic coffee"], ["قهوة مختصة", "Specialty coffee"]], 0),
      mcq("هذا ولا هذا؟", "This or that?", [["العلا", "AlUla"], ["جدة", "Jeddah"]], 0),
      mcq("هذا ولا هذا؟", "This or that?", [["صباح الجمعة", "Friday morning"], ["مساء الجمعة", "Friday evening"]], 0),
    ],
  },
];

export const SEED_PLANS = [
  {
    id: "free",
    nameAr: "مجاني",
    nameEn: "Free",
    price: 0,
    interval: "free",
    featuresAr: ["ألعاب مختارة", "غرف محدودة يوميًا", "حتى 14 لاعبًا"],
    featuresEn: ["A selection of games", "A daily room limit", "Up to 14 players"],
    sort: 1,
  },
  {
    id: "monthly",
    nameAr: "بريميوم شهري",
    nameEn: "Premium monthly",
    price: 29,
    interval: "month",
    featuresAr: ["كل الألعاب", "غرف بلا حد يومي", "بدون مساحة إعلانية", "تخصيص الوقت والجولات"],
    featuresEn: ["Every game", "No daily room cap", "No house ad", "Custom timing and rounds"],
    sort: 2,
  },
  {
    id: "yearly",
    nameAr: "بريميوم سنوي",
    nameEn: "Premium yearly",
    price: 99,
    interval: "year",
    featuresAr: ["كل مزايا الشهري", "سعر السنة أوفر", "ألعاب تُضاف لاحقًا"],
    featuresEn: ["Everything in monthly", "A lower yearly price", "Games added later"],
    sort: 3,
  },
  {
    id: "lifetime",
    nameAr: "مدى الحياة",
    nameEn: "Lifetime",
    price: 199,
    interval: "lifetime",
    featuresAr: ["كل الألعاب", "دفعة واحدة", "غرف خاصة بلا انتهاء الاشتراك"],
    featuresEn: ["Every game", "One payment", "Private rooms without a renewal"],
    sort: 4,
  },
];

export const SEED_PROMOS = [
  { code: "LAMMA50", kind: "percent", amount: 50 },
  { code: "LAMMA30", kind: "days", amount: 30 },
  { code: "LAMMALIFE", kind: "lifetime", amount: 0 },
];
