-- Bravo challenge: a playable choice game with category-tagged questions.
-- Categories match the room option in /play: movies, puzzles, sports, culture.
insert into games (id, name_ar, name_en, description_ar, description_en, category, engine, min_players, max_players, default_seconds, default_rounds, visible, status, source, sort_order, icon)
values ('bravo-party', 'تحدي برافو', 'Bravo Challenge', 'تخمين جماعي وفئات سريعة', 'Group guessing and quick categories', 'party', 'choice', 2, 14, 20, 6, true, 'published', 'system', 50, 'Gamepad2')
on conflict (id) do nothing;

insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اسم الساحر الذي يدرس في مدرسة هوجورتس؟', 'Which wizard studies at Hogwarts?', 'choice', '[{"id": "c0", "ar": "هاري بوتر", "en": "Harry Potter"}, {"id": "c1", "ar": "فرودو", "en": "Frodo"}, {"id": "c2", "ar": "أرثر", "en": "Arthur"}, {"id": "c3", "ar": "لوك", "en": "Luke"}]'::jsonb, 'c0', 'movies', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Which wizard studies at Hogwarts?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اسم بطل أنمي ناروتو؟', 'What is the name of the anime hero Naruto?', 'choice', '[{"id": "c0", "ar": "ناروتو أوزوماكي", "en": "Naruto Uzumaki"}, {"id": "c1", "ar": "غوكو", "en": "Goku"}, {"id": "c2", "ar": "ليفاي", "en": "Levi"}, {"id": "c3", "ar": "لوفي", "en": "Luffy"}]'::jsonb, 'c0', 'movies', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the name of the anime hero Naruto?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'من أخرج فيلم Titanic؟', 'Who directed Titanic?', 'choice', '[{"id": "c0", "ar": "جيمس كاميرون", "en": "James Cameron"}, {"id": "c1", "ar": "ستيفن سبيلبرغ", "en": "Steven Spielberg"}, {"id": "c2", "ar": "كريستوفر نولان", "en": "Christopher Nolan"}, {"id": "c3", "ar": "ريدلي سكوت", "en": "Ridley Scott"}]'::jsonb, 'c0', 'movies', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Who directed Titanic?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اسم الأسد الصغير في فيلم The Lion King؟', 'What is the name of the young lion in The Lion King?', 'choice', '[{"id": "c0", "ar": "سمبا", "en": "Simba"}, {"id": "c1", "ar": "موفاسا", "en": "Mufasa"}, {"id": "c2", "ar": "سكار", "en": "Scar"}, {"id": "c3", "ar": "تيمون", "en": "Timon"}]'::jsonb, 'c0', 'movies', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the name of the young lion in The Lion King?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اسم قبعة لوفي في ون بيس؟', 'What is Luffy''s hat called in One Piece?', 'choice', '[{"id": "c0", "ar": "قبعة القش", "en": "Straw Hat"}, {"id": "c1", "ar": "القبعة السوداء", "en": "Black Hat"}, {"id": "c2", "ar": "القبعة الذهبية", "en": "Golden Hat"}, {"id": "c3", "ar": "القبعة البيضاء", "en": "White Hat"}]'::jsonb, 'c0', 'movies', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is Luffy''s hat called in One Piece?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اسم شخصية فيلم Frozen التي تتحكم بالثلج؟', 'Which Frozen character controls ice?', 'choice', '[{"id": "c0", "ar": "إلسا", "en": "Elsa"}, {"id": "c1", "ar": "آنا", "en": "Anna"}, {"id": "c2", "ar": "ريبونزل", "en": "Rapunzel"}, {"id": "c3", "ar": "مولان", "en": "Mulan"}]'::jsonb, 'c0', 'movies', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Which Frozen character controls ice?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم عدد أضلاع المسدس؟', 'How many sides does a hexagon have?', 'choice', '[{"id": "c0", "ar": "4", "en": "4"}, {"id": "c1", "ar": "5", "en": "5"}, {"id": "c2", "ar": "6", "en": "6"}, {"id": "c3", "ar": "8", "en": "8"}]'::jsonb, 'c2', 'puzzles', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'How many sides does a hexagon have?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما الشيء الذي كلما أخذت منه صار أكبر؟', 'What gets bigger the more you take from it?', 'choice', '[{"id": "c0", "ar": "الحفرة", "en": "A hole"}, {"id": "c1", "ar": "الظل", "en": "A shadow"}, {"id": "c2", "ar": "الساعة", "en": "A clock"}, {"id": "c3", "ar": "الصابون", "en": "Soap"}]'::jsonb, 'c0', 'puzzles', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What gets bigger the more you take from it?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما أسرع حيوان بري؟', 'What is the fastest land animal?', 'choice', '[{"id": "c0", "ar": "الأسد", "en": "Lion"}, {"id": "c1", "ar": "الفهد", "en": "Cheetah"}, {"id": "c2", "ar": "الحصان", "en": "Horse"}, {"id": "c3", "ar": "الغزال", "en": "Gazelle"}]'::jsonb, 'c1', 'puzzles', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the fastest land animal?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم يساوي 12 × 12؟', 'What is 12 × 12?', 'choice', '[{"id": "c0", "ar": "124", "en": "124"}, {"id": "c1", "ar": "144", "en": "144"}, {"id": "c2", "ar": "132", "en": "132"}, {"id": "c3", "ar": "156", "en": "156"}]'::jsonb, 'c1', 'puzzles', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is 12 × 12?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم عدد كواكب النظام الشمسي؟', 'How many planets are in the solar system?', 'choice', '[{"id": "c0", "ar": "7", "en": "7"}, {"id": "c1", "ar": "8", "en": "8"}, {"id": "c2", "ar": "9", "en": "9"}, {"id": "c3", "ar": "10", "en": "10"}]'::jsonb, 'c1', 'puzzles', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'How many planets are in the solar system?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'أي هذه الأعداد أولي؟', 'Which of these numbers is prime?', 'choice', '[{"id": "c0", "ar": "9", "en": "9"}, {"id": "c1", "ar": "15", "en": "15"}, {"id": "c2", "ar": "17", "en": "17"}, {"id": "c3", "ar": "21", "en": "21"}]'::jsonb, 'c2', 'puzzles', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Which of these numbers is prime?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم لاعباً في الفريق داخل الملعب في كرة القدم؟', 'How many players per team are on the pitch in football?', 'choice', '[{"id": "c0", "ar": "9", "en": "9"}, {"id": "c1", "ar": "10", "en": "10"}, {"id": "c2", "ar": "11", "en": "11"}, {"id": "c3", "ar": "12", "en": "12"}]'::jsonb, 'c2', 'sports', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'How many players per team are on the pitch in football?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'في أي دولة أقيمت كأس العالم 2022؟', 'Which country hosted the 2022 World Cup?', 'choice', '[{"id": "c0", "ar": "قطر", "en": "Qatar"}, {"id": "c1", "ar": "روسيا", "en": "Russia"}, {"id": "c2", "ar": "البرازيل", "en": "Brazil"}, {"id": "c3", "ar": "ألمانيا", "en": "Germany"}]'::jsonb, 'c0', 'sports', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Which country hosted the 2022 World Cup?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'أي منتخب فاز بكأس العالم 2018؟', 'Which team won the 2018 World Cup?', 'choice', '[{"id": "c0", "ar": "فرنسا", "en": "France"}, {"id": "c1", "ar": "كرواتيا", "en": "Croatia"}, {"id": "c2", "ar": "بلجيكا", "en": "Belgium"}, {"id": "c3", "ar": "إنجلترا", "en": "England"}]'::jsonb, 'c0', 'sports', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Which team won the 2018 World Cup?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم دقيقة مدة الشوط الواحد في كرة القدم؟', 'How long is one half of a football match?', 'choice', '[{"id": "c0", "ar": "30", "en": "30 minutes"}, {"id": "c1", "ar": "40", "en": "40 minutes"}, {"id": "c2", "ar": "45", "en": "45 minutes"}, {"id": "c3", "ar": "60", "en": "60 minutes"}]'::jsonb, 'c2', 'sports', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'How long is one half of a football match?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما اللون الذي يُشهر للاعب المطرود من الملعب؟', 'What colour card sends a player off?', 'choice', '[{"id": "c0", "ar": "الأصفر", "en": "Yellow"}, {"id": "c1", "ar": "الأحمر", "en": "Red"}, {"id": "c2", "ar": "الأزرق", "en": "Blue"}, {"id": "c3", "ar": "الأخضر", "en": "Green"}]'::jsonb, 'c1', 'sports', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What colour card sends a player off?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'في أي مدينة يُقام سباق جائزة موناكو للفورمولا 1؟', 'In which city is the Monaco Formula 1 Grand Prix held?', 'choice', '[{"id": "c0", "ar": "موناكو", "en": "Monaco"}, {"id": "c1", "ar": "ميلانو", "en": "Milan"}, {"id": "c2", "ar": "ليون", "en": "Lyon"}, {"id": "c3", "ar": "برشلونة", "en": "Barcelona"}]'::jsonb, 'c0', 'sports', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'In which city is the Monaco Formula 1 Grand Prix held?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما عاصمة اليابان؟', 'What is the capital of Japan?', 'choice', '[{"id": "c0", "ar": "كيوتو", "en": "Kyoto"}, {"id": "c1", "ar": "طوكيو", "en": "Tokyo"}, {"id": "c2", "ar": "أوساكا", "en": "Osaka"}, {"id": "c3", "ar": "هيروشيما", "en": "Hiroshima"}]'::jsonb, 'c1', 'culture', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the capital of Japan?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما أكبر محيط في العالم؟', 'What is the largest ocean?', 'choice', '[{"id": "c0", "ar": "الأطلسي", "en": "Atlantic"}, {"id": "c1", "ar": "الهندي", "en": "Indian"}, {"id": "c2", "ar": "الهادئ", "en": "Pacific"}, {"id": "c3", "ar": "المتجمد الشمالي", "en": "Arctic"}]'::jsonb, 'c2', 'culture', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the largest ocean?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'كم عدد أيام الأسبوع؟', 'How many days are in a week?', 'choice', '[{"id": "c0", "ar": "5", "en": "5"}, {"id": "c1", "ar": "6", "en": "6"}, {"id": "c2", "ar": "7", "en": "7"}, {"id": "c3", "ar": "8", "en": "8"}]'::jsonb, 'c2', 'culture', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'How many days are in a week?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما أكبر قارة في العالم؟', 'What is the largest continent?', 'choice', '[{"id": "c0", "ar": "أفريقيا", "en": "Africa"}, {"id": "c1", "ar": "آسيا", "en": "Asia"}, {"id": "c2", "ar": "أوروبا", "en": "Europe"}, {"id": "c3", "ar": "أمريكا الشمالية", "en": "North America"}]'::jsonb, 'c1', 'culture', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the largest continent?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'من كتب رواية الأمير الصغير؟', 'Who wrote The Little Prince?', 'choice', '[{"id": "c0", "ar": "أنطوان دو سانت إكزوبيري", "en": "Antoine de Saint-Exupéry"}, {"id": "c1", "ar": "فيكتور هوغو", "en": "Victor Hugo"}, {"id": "c2", "ar": "جول فيرن", "en": "Jules Verne"}, {"id": "c3", "ar": "تولستوي", "en": "Tolstoy"}]'::jsonb, 'c0', 'culture', 'medium', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'Who wrote The Little Prince?');
insert into questions (game_id, prompt_ar, prompt_en, kind, choices, correct, category, difficulty, points, status, source) select 'bravo-party', 'ما العملة الرسمية للمملكة العربية السعودية؟', 'What is the official currency of Saudi Arabia?', 'choice', '[{"id": "c0", "ar": "الدينار", "en": "Dinar"}, {"id": "c1", "ar": "الدرهم", "en": "Dirham"}, {"id": "c2", "ar": "الريال السعودي", "en": "Saudi Riyal"}, {"id": "c3", "ar": "الجنيه", "en": "Pound"}]'::jsonb, 'c2', 'culture', 'easy', 100, 'published', 'bravo' where not exists (select 1 from questions x where x.game_id = 'bravo-party' and x.prompt_en = 'What is the official currency of Saudi Arabia?');
