/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as HostCodeRouteImport } from './routes/host/$code'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as PadCodeRouteImport } from './routes/pad/$code'
import { Route as PlayCodeRouteImport } from './routes/play_.$code'
import { Route as TvCodeRouteImport } from './routes/tv/$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCodeRoute = HostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PadCodeRoute = PadCodeRouteImport.update({
  id: '/pad/$code',
  path: '/pad/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play_/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TvCodeRoute = TvCodeRouteImport.update({
  id: '/tv/$code',
  path: '/tv/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/games/$slug': typeof GamesSlugRoute
  '/host/$code': typeof HostCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/pad/$code': typeof PadCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/tv/$code': typeof TvCodeRoute
  '/games/': typeof GamesIndexRoute
  '/join/': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/games/$slug': typeof GamesSlugRoute
  '/host/$code': typeof HostCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/pad/$code': typeof PadCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/tv/$code': typeof TvCodeRoute
  '/games': typeof GamesIndexRoute
  '/join': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/games/$slug': typeof GamesSlugRoute
  '/host/$code': typeof HostCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/pad/$code': typeof PadCodeRoute
  '/play_/$code': typeof PlayCodeRoute
  '/tv/$code': typeof TvCodeRoute
  '/games/': typeof GamesIndexRoute
  '/join/': typeof JoinIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/play'
    | '/premium'
    | '/profile'
    | '/sitemap.xml'
    | '/games/$slug'
    | '/host/$code'
    | '/join/$code'
    | '/pad/$code'
    | '/play/$code'
    | '/tv/$code'
    | '/games/'
    | '/join/'
    | '/api/auth/$'
    | '/api/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/play'
    | '/premium'
    | '/profile'
    | '/sitemap.xml'
    | '/games/$slug'
    | '/host/$code'
    | '/join/$code'
    | '/pad/$code'
    | '/play/$code'
    | '/tv/$code'
    | '/games'
    | '/join'
    | '/api/auth/$'
    | '/api/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/play'
    | '/premium'
    | '/profile'
    | '/sitemap.xml'
    | '/games/$slug'
    | '/host/$code'
    | '/join/$code'
    | '/pad/$code'
    | '/play_/$code'
    | '/tv/$code'
    | '/games/'
    | '/join/'
    | '/api/auth/$'
    | '/api/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GamesSlugRoute: typeof GamesSlugRoute
  HostCodeRoute: typeof HostCodeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  PadCodeRoute: typeof PadCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
  TvCodeRoute: typeof TvCodeRoute
  GamesIndexRoute: typeof GamesIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$code': {
      id: '/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof HostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pad/$code': {
      id: '/pad/$code'
      path: '/pad/$code'
      fullPath: '/pad/$code'
      preLoaderRoute: typeof PadCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_/$code': {
      id: '/play_/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$code': {
      id: '/tv/$code'
      path: '/tv/$code'
      fullPath: '/tv/$code'
      preLoaderRoute: typeof TvCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GamesSlugRoute: GamesSlugRoute,
  HostCodeRoute: HostCodeRoute,
  JoinCodeRoute: JoinCodeRoute,
  PadCodeRoute: PadCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
  TvCodeRoute: TvCodeRoute,
  GamesIndexRoute: GamesIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
